"use client";

import { FormEvent, KeyboardEvent, useRef, useState } from "react";
import { useParams } from "next/navigation";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import Shell from "@/components/workspace/shell";
import { api } from "@/lib/api";

type Member={id:string;name:string;role:string};
function queryAfterAt(value:string){return value.match(/(?:^|\s)@([^\s@]*)$/)?.[1]?.toLowerCase()}
function MentionInput({value,onChange,members,placeholder,multiline=false}:{value:string;onChange:(value:string)=>void;members:Member[];placeholder:string;multiline?:boolean}){const input=useRef<HTMLInputElement&HTMLTextAreaElement>(null),[selected,setSelected]=useState(0);const query=queryAfterAt(value);const suggestions=query===undefined?[]:members.filter(member=>member.name.toLowerCase().includes(query)).slice(0,6);function choose(member:Member){const next=value.replace(/@([^\s@]*)$/,`@${member.name} `);onChange(next);requestAnimationFrame(()=>input.current?.focus())}function keydown(event:KeyboardEvent<HTMLInputElement|HTMLTextAreaElement>){if(!suggestions.length)return;if(event.key==="ArrowDown"){event.preventDefault();setSelected(current=>(current+1)%suggestions.length)}if(event.key==="ArrowUp"){event.preventDefault();setSelected(current=>(current-1+suggestions.length)%suggestions.length)}if(event.key==="Enter"&&!multiline){if(suggestions[selected]){event.preventDefault();choose(suggestions[selected])}}if(event.key==="Tab"&&suggestions[selected]){event.preventDefault();choose(suggestions[selected])}}const fieldProps={ref:input as any,value,onChange:(event:any)=>{onChange(event.target.value);setSelected(0)},onKeyDown:keydown,placeholder,className:"border rounded px-3 py-2 w-full bg-white"};return <div className="relative">{multiline?<textarea {...fieldProps} className="border rounded px-3 py-2 min-h-28 w-full bg-white"/>:<input {...fieldProps}/>} {suggestions.length>0&&<div className="absolute z-30 left-0 right-0 mt-1 bg-white border rounded-lg shadow-lg overflow-hidden">{suggestions.map((member,index)=><button type="button" key={member.id} className={`w-full text-left px-3 py-2 flex items-center gap-2 ${index===selected?"bg-emerald-50":"hover:bg-slate-50"}`} onMouseDown={event=>{event.preventDefault();choose(member)}}><span className="w-7 h-7 rounded-full bg-emerald-100 grid place-items-center text-xs">{member.name.slice(0,2).toUpperCase()}</span><span><b>{member.name}</b><small className="block muted">{member.role.toLowerCase()}</small></span></button>)}</div>}</div>}
function MentionText({content,members}:{content:string;members:Member[]}){const names=members.map(member=>member.name.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")).sort((a,b)=>b.length-a.length);if(!names.length)return <>{content}</>;const pieces=content.split(new RegExp(`(@(?:${names.join("|")}))`,"gi"));return <>{pieces.map((piece,index)=>piece.startsWith("@")?<mark key={index} className="bg-emerald-100 text-emerald-900 rounded px-1 font-medium">{piece}</mark>:piece)}</>}
export default function Discussions(){const {workspaceId}=useParams<{workspaceId:string}>(),[title,setTitle]=useState(""),[content,setContent]=useState(""),qc=useQueryClient();const members=useQuery({queryKey:["members",workspaceId],queryFn:()=>api<Member[]>(`/api/workspaces/${workspaceId}/members`)}),threads=useQuery({queryKey:["discussions",workspaceId],queryFn:()=>api<any[]>(`/api/workspaces/${workspaceId}/discussions`)});const create=useMutation({mutationFn:()=>api(`/api/workspaces/${workspaceId}/discussions`,{method:"POST",body:JSON.stringify({title:title||null,content})}),onSuccess:()=>{setTitle("");setContent("");qc.invalidateQueries({queryKey:["discussions",workspaceId]})}});function submit(event:FormEvent){event.preventDefault();create.mutate()}return <Shell workspaceId={workspaceId}><div className="rounded-xl p-6 bg-gradient-to-br from-emerald-950 to-emerald-800 text-white"><p className="text-emerald-200 text-sm font-medium">COLLABORATION</p><h1 className="text-3xl font-semibold mt-1">Research discussions</h1><p className="text-emerald-100 mt-2">Challenge evidence, share context, and bring the right collaborator into the conversation.</p></div><form className="panel p-5 grid gap-3 mt-5 shadow-sm" onSubmit={submit}><input className="border rounded px-3 py-2" placeholder="Discussion title (optional)" value={title} onChange={e=>setTitle(e.target.value)}/><MentionInput value={content} onChange={setContent} members={members.data||[]} multiline placeholder="Start a discussion. Type @ to notify a collaborator…"/><button className="btn btn-primary justify-self-start" disabled={create.isPending}>{create.isPending?"Creating…":"Start discussion"}</button>{create.error&&<p className="text-red-700">{create.error.message}</p>}</form><div className="grid gap-4 mt-6">{threads.data?.map(thread=><DiscussionCard key={thread.id} thread={thread} members={members.data||[]}/>)}{threads.data?.length===0&&<div className="panel p-8 text-center muted">No discussions yet. Start one to get focused research feedback.</div>}</div></Shell>}
function DiscussionCard({thread,members}:{thread:any;members:Member[]}){const detail=useQuery({queryKey:["discussion",thread.id],queryFn:()=>api<any>(`/api/discussions/${thread.id}`)}),[content,setContent]=useState(""),qc=useQueryClient();async function reply(event:FormEvent){event.preventDefault();await api(`/api/discussions/${thread.id}/messages`,{method:"POST",body:JSON.stringify({content})});setContent("");qc.invalidateQueries({queryKey:["discussion",thread.id]})}return <article className="panel p-5 shadow-sm"><div className="flex justify-between gap-3"><div><span className="text-xs text-emerald-700 font-medium uppercase tracking-wide">{thread.scope.toLowerCase()} discussion</span><h2 className="font-semibold text-lg">{thread.title||"Untitled discussion"}</h2></div></div><div className="mt-4 space-y-3">{detail.data?.messages.map((message:any)=><div className="border-l-2 border-emerald-200 pl-3" key={message.id}><p className="leading-6"><MentionText content={message.content} members={members}/></p><p className="muted text-sm mt-1">{message.author.name}</p></div>)}</div><form className="mt-5" onSubmit={reply}><MentionInput value={content} onChange={setContent} members={members} placeholder="Reply, or type @ to mention a collaborator…"/><button className="btn mt-2">Reply</button></form></article>}
