"use client";
import { useState } from "react";
import { api } from "@/lib/api";

export default function InviteButton({ workspaceId }: { workspaceId: string }) {
  const [open,setOpen]=useState(false), [role,setRole]=useState("EDITOR"), [expires,setExpires]=useState(7), [link,setLink]=useState(""), [error,setError]=useState("");
  async function create() { setError(""); try { const invite=await api<any>(`/api/workspaces/${workspaceId}/invites`,{method:"POST",body:JSON.stringify({role,expires_in_days:expires})}); setLink(`${window.location.origin}${invite.invite_path}`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not create invite."); } }
  async function copy() { if(link) await navigator.clipboard.writeText(link); }
  return <><button className="btn btn-primary" onClick={()=>setOpen(true)}>Invite</button>{open&&<div className="fixed inset-0 bg-slate-950/30 grid place-items-center p-4 z-50"><section className="panel bg-white p-6 w-full max-w-md shadow-xl"><div className="flex justify-between"><h2 className="text-xl font-semibold">Invite collaborators</h2><button className="btn" onClick={()=>setOpen(false)}>Close</button></div><p className="muted mt-1">Share a secure link with a workspace collaborator.</p><label className="block mt-4 text-sm">Role<select className="border rounded px-3 py-2 block w-full mt-1" value={role} onChange={e=>setRole(e.target.value)}><option value="EDITOR">Editor</option><option value="VIEWER">Viewer</option></select></label><label className="block mt-3 text-sm">Expires<select className="border rounded px-3 py-2 block w-full mt-1" value={expires} onChange={e=>setExpires(Number(e.target.value))}><option value={1}>1 day</option><option value={7}>7 days</option><option value={30}>30 days</option></select></label>{link?<div className="mt-4"><label className="text-sm">Share link</label><div className="flex gap-2 mt-1"><input className="border rounded px-3 py-2 flex-1 text-sm" readOnly value={link}/><button className="btn btn-primary" onClick={copy}>Copy link</button></div></div>:<button className="btn btn-primary mt-5" onClick={create}>Generate secure link</button>}{error&&<p className="text-red-700 text-sm mt-3">{error}</p>}</section></div>}</>;
}
